-- 创建 daily_news 表
CREATE TABLE IF NOT EXISTS daily_news (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  date TEXT NOT NULL,
  data JSONB NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 创建唯一索引（防止同一天重复数据）
CREATE UNIQUE INDEX IF NOT EXISTS daily_news_date_key
ON daily_news(date);

-- 创建更新时间触发器
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_daily_news_updated_at
BEFORE UPDATE ON daily_news
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- 插入测试数据
INSERT INTO daily_news (date, data)
VALUES (
  '2025-01-18',
  '[
    {
      "id": 1,
      "rank": 1,
      "summary": "测试新闻摘要",
      "content": "这是一条测试新闻，用于验证数据库连接是否正常。",
      "date": "2025-01-18",
      "question": "测试题目：根据上述内容，简要概括新闻要点。",
      "answer": "这是一条测试新闻，主要功能是验证数据库连接是否正常工作。"
    }
  ]'::jsonb
)
ON CONFLICT (date) DO NOTHING;

-- 查询测试数据（验证是否成功）
SELECT * FROM daily_news LIMIT 5;
